server:
  port: 7654
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/notes_app?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    org.springframework:
      data: debug
      security: debug
sentry:
  dsn: https://9e6da7cae58c49a1bbee175846275e43@sentry.io/1220905  # Bohan

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "

---
spring:
  profiles: test
server:
  port: 7655


---
spring:
  profiles: dev
server:
  port: 7656
sentry:
  dsn: https://6acec681efdc47e7b1de0d079ee4511a@sentry.io/217520  # Panmax
