server:
  port: 7654
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/notes_app?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    org.springframework:
      data: debug
      security: debug

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
